# Generated by Django 4.1.2 on 2022-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Backend', models.BooleanField(default=True, null=True)),
                ('Bio', models.TextField(null=True)),
            ],
        ),
    ]
