# Generated by Django 4.1.2 on 2022-10-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HNGAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user_name',
        ),
    ]
