# Generated by Django 4.1 on 2022-10-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HNGAPP', '0002_rename_username_profile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Backend',
            new_name='backend',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='slackUsername',
        ),
    ]
